### ISSUE TITLE
Make paths based on base_path variable

### ISSUE THREAD

**Issue by MarinusVanDijk** [LiacsProjects/linkingUCD_code#5]
https://github.com/LiacsProjects/linkingUCD_code/blob/ceb8832babbe25db558e7fa6a057bcf81e0a9838/Dashboard/figures/introfigures.py#L10

Make paths to pictures based on the base_path variable. Else it will not run on the server.

```
from pathlib import Path
import os

base_path = Path(os.environ['DASHBOARD_BASEPATH'])

card_professor = dbc.Card([
    dbc.CardImg(
        src= base_path / "assets/professors_780x400.jpeg",
        top=True,
        style={"opacity": 0.5},
        class_name="cardImg"
    ),
...
```

**Comment by BvYp** [comment]
File introfigures.py aangepast.
Maar iets andere oplossing : src= "../assets/professors_780x400.jpeg"
De hierboven genoemde oplossing werkte niet in de windows omgeving. Ik snap niet waarom niet.
Op nog drie plaatsen in de file dezelfde aanpassing gemaakt.

**Comment by MarinusVanDijk** [comment]
Ik denk dat deze code er nog bij moet:

```
import Add_environment_variable
...
```

Op de server wordt deze onderdrukt.

**Comment by BvYp** [comment]
Hallo Richard,

 

Ik meen me te herinneren dat voor de server in plaats van dit Add_environment_variable.py script een programma dashboard.wsgi gedraaid moest worden.

Ik weet echter niet of dat vanuit Python gedaan moet worden, ik denk het niet eigenlijk.

In de dashboard.py file heb ik nog een regel “server = app.server” toegevoegd, die ontbrak en is wel nodig voor de server versie.

De aanpassingen weer gepusht.

Ik hoop dat dit voldoende is om de applicatie werkend te krijgen.

 

Met vriendelijke groeten,

 

Ben van Yperen

 

Van: Richard van Dijk ***@***.***> 
Verzonden: woensdag 4 januari 2023 19:22
Aan: LiacsProjects/linkingUCD_code ***@***.***>
CC: BvYp ***@***.***>; Assign ***@***.***>
Onderwerp: Re: [LiacsProjects/linkingUCD_code] Make paths based on base_path variable (Issue #5)

 

Ik denk dat deze code er nog bij moet:

import Add_environment_variable
...

Op de server wordt deze onderdrukt.

**Comment by MarinusVanDijk** [comment]
Klopt. De server zet zijn environment variable zoals jij dat doet in Add_environment_variable.py.

Wat ik bedoel is dat op 1 plek deze variabele wordt gezet. De code heeft dan verder geen aanpassing nodig. 

We moeten denk ik in de code een ruler maken die de code lokaal en op de server laat werken.
