### ISSUE TITLE
Error loading layout on server, downgrade to Python 3.6?

### ISSUE THREAD

**Issue by MarinusVanDijk** [LiacsProjects/linkingUCD_code#7]
Still problems with the server:

![image](https://user-images.githubusercontent.com/37830964/211265609-1f7f32b5-53d1-4db0-b5d7-ebe5c46bbc42.png)

Error in loading the new layout.

Perhaps a problem with the Python version 3.6 on the server?

**Comment by BvYp** [comment]
Op mijn desktop computer heb ik Python 3.6 geïnstalleerd en beide applicaties: het LUCD dashboard en  het Leiden 1848 dashboard hiermee laten werken. Voor beide lukte dat na het opnieuw installeren van de nodige packages Plus dat in de laatste programma regel, de app.run_server command, de debug optie op False gezet moest worden.  
Dit lukte ook met versie 3.9 die ook op deze computer stond.

C:\Users\Ben\AppData\Local\Programs\Python\Python36\python.exe "C:\Users\Ben\PycharmProjects\LUCD_PY36\Linking UCD - dashboard\dashboard.py" 
Operating system: Windows-10-10.0.19041-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
DASHBOARD_BASEPATH c:/users/Ben/PyCharmProjects/LUCD_Py36/Linking UCD - dashboard/
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'dashboard' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
